### ISSUE TITLE
Nothing is display when i try to use annotation-viewer tag

### ISSUE THREAD

**Issue by benjaminParisel** [publicMindee/mindee-js#1]
I would use your **annotation-viewer web-component** but I'm facing any issues.

### Steps to Reproduce

1. npm install mindee-js
2.  add `import 'mindee-js/build/web-components'; on top of my files _(FYI: if i follow readme, `mindee-js/web-components` is not exist)_
3. I declare in my app: html`<annotation-viewer image="pathToMyImages">` but nothing is displaying.
4. Nothing is displayed in my app.

I give you a screenshot of dom on my application.

![image](https://user-images.githubusercontent.com/25297128/101795714-74c86780-3b08-11eb-8eac-109987879439.png)

Did I miss something to use it?

Note:
*  i have already trying with 1.0.0.rc-01 and 1.0.0.rc-02.
* With you react-mindee-js, same expense is displaying fine.

**Comment by AbdelfattahSekak** [comment]
Regarding the second step, the build path should be fixed in the next release. 
If nothing is displayed, you may need to pass a style object to both `annotation-viewer` and `annotation-lens` width those properties `{ display: "flex", width: 300, height: 300 }`. In fact, canvases should be forced to take non-null height and width.

**Comment by AbdelfattahSekak** [comment]
The last commits should fix both issues. README is up to date with the right path to web components file.
In addition, a default style has been provided to both web components  in order to display correctly the canvases without any additional styles.

**Comment by benjaminParisel** [comment]
Nice! Thank you for your response. I will check and tested I when a new release candidate is availaible.

FYI: Be careful, the readme is not up to date, it's mentioned some react libraries.

**Comment by benjaminParisel** [comment]
Hi ! Do you have an idea about the date when this next release will be published ?

**Comment by AbdelfattahSekak** [comment]
We have erased the old releases. You can now check the new v1.0.0-rc tag. It includes all the changes related to this issue.

**Comment by benjaminParisel** [comment]
Thanks you ! I will check and use it next Thursday.
